{
 "title": "FSxN: LUN",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\"}, datacenter)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\",datacenter=~\"$Datacenter\"}, cluster)"
    }
   },
   {
    "name": "SVM",
    "query": {
     "query": "label_values(lun_labels{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}, svm)"
    }
   },
   {
    "name": "Volume",
    "query": {
     "query": "label_values(lun_labels{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\"}, volume)"
    }
   },
   {
    "name": "LUN",
    "query": {
     "query": "label_values(lun_labels{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\", volume=~\"$Volume|\"},lun)"
    }
   },
   {
    "name": "TopResources",
    "query": "1,2,3,4,5,6,8,10,15,25,50,100,250,500"
   }
  ]
 },
 "panels": [
  {
   "title": "Highlights",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopResources Luns by Average Read Latency",
     "type": "stat",
     "description": "Average Latency of top $TopResources volumes.",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg(topk($TopResources, lun_avg_read_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",lun=~\"$LUN\"}))"
      }
     ]
    },
    {
     "title": "Top $TopResources Luns by Average Write Latency",
     "type": "stat",
     "description": "Average Latency of top $TopResources volumes.",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg(topk($TopResources, lun_avg_write_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",lun=~\"$LUN\"}))"
      }
     ]
    },
    {
     "title": "Top $TopResources Luns by Read Throughput",
     "type": "stat",
     "description": "Throughput of top $TopResources volumes.",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(topk($TopResources, lun_read_data{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",lun=~\"$LUN\"}))"
      }
     ]
    },
    {
     "title": "Top $TopResources Luns by Write Throughput",
     "type": "stat",
     "description": "Throughput of top $TopResources volumes.",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(topk($TopResources, lun_write_data{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",lun=~\"$LUN\"}))"
      }
     ]
    },
    {
     "title": "Top $TopResources Luns by Read IOPs",
     "type": "stat",
     "description": "IOPs of top $TopResources volumes.",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(topk($TopResources, lun_read_ops{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",lun=~\"$LUN\"}))"
      }
     ]
    },
    {
     "title": "Top $TopResources Luns by Write IOPs",
     "type": "stat",
     "description": "IOPs of top $TopResources volumes.",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(topk($TopResources, lun_write_ops{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",lun=~\"$LUN\"}))"
      }
     ]
    }
   ]
  },
  {
   "title": "LUN Table",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopResources Luns by Read Latency",
     "type": "table",
     "description": "Average read latency in microseconds for all operations on the LUN.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "lun_avg_read_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",lun=~\"$LUN\"} \n  and \ntopk($TopResources, lun_avg_read_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",lun=~\"$LUN\"} @ end())"
      }
     ]
    },
    {
     "title": "Top $TopResources Luns by Read Throughput",
     "type": "table",
     "description": "Read bytes.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "lun_read_data{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",lun=~\"$LUN\"} \n  and \ntopk($TopResources, lun_read_data{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",lun=~\"$LUN\"} @ end())"
      }
     ]
    },
    {
     "title": "Top $TopResources Luns by Read IOPS",
     "type": "table",
     "description": "Number of read operations.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "lun_read_ops{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",lun=~\"$LUN\"} \n  and \ntopk($TopResources, lun_read_ops{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",lun=~\"$LUN\"} @ end())"
      }
     ]
    },
    {
     "title": "Top $TopResources Luns by Write Latency",
     "type": "table",
     "description": "Average write latency in microseconds for all operations on the LUN.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "lun_avg_write_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",lun=~\"$LUN\"} \nand \ntopk($TopResources, lun_avg_write_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",lun=~\"$LUN\"} @ end())",
       "legendFormat": "{{svm}}/{{volume}}/{{lun}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Luns by Write Throughput",
     "type": "table",
     "description": "Write bytes.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "lun_write_data{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",lun=~\"$LUN\"} \nand \ntopk($TopResources, lun_write_data{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",lun=~\"$LUN\"} @ end())"
      }
     ]
    },
    {
     "title": "Top $TopResources Luns by Write IOPS",
     "type": "table",
     "description": "Number of write operations.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "lun_write_ops{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",lun=~\"$LUN\"} \nand \ntopk($TopResources, lun_write_ops{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",lun=~\"$LUN\"} @ end())"
      }
     ]
    },
    {
     "title": "LUNS in Cluster",
     "type": "table",
     "description": "LUN details.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "lun_labels{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",lun=~\"$LUN\"}"
      },
      {
       "expr": "lun_new_status{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",lun=~\"$LUN\"}"
      },
      {
       "expr": "lun_size{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",lun=~\"$LUN\"}"
      },
      {
       "expr": "lun_size_used{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",lun=~\"$LUN\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Top LUN Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopResources Luns by Average Read Latency",
     "type": "timeseries",
     "description": "Average read latency in microseconds for all operations on the LUN.",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "lun_avg_read_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",lun=~\"$LUN\"} \n  and \ntopk($TopResources, avg_over_time(lun_avg_read_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",lun=~\"$LUN\"}[3h] @ end()))",
       "legendFormat": "{{svm}} / {{volume}} / {{lun}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Luns by Read Throughput",
     "type": "timeseries",
     "description": "Read bytes.",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "lun_read_data{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",lun=~\"$LUN\"} \n  and \ntopk($TopResources, avg_over_time(lun_read_data{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",lun=~\"$LUN\"}[3h] @ end()))",
       "legendFormat": "{{svm}} / {{volume}} / {{lun}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Luns by Read IOPs",
     "type": "timeseries",
     "description": "Number of read operations.",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "lun_read_ops{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",lun=~\"$LUN\"} \n  and \ntopk($TopResources, avg_over_time(lun_read_ops{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",lun=~\"$LUN\"}[3h] @ end()))",
       "legendFormat": "{{svm}} / {{volume}} / {{lun}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Luns by Average Write Latency",
     "type": "timeseries",
     "description": "Average write latency in microseconds for all operations on the LUN.",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "lun_avg_write_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",lun=~\"$LUN\"} \n  and \ntopk($TopResources, avg_over_time(lun_avg_write_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",lun=~\"$LUN\"}[3h] @ end()))",
       "legendFormat": "{{svm}} / {{volume}} / {{lun}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Luns by Write Throughput",
     "type": "timeseries",
     "description": "Write bytes.",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "lun_write_data{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",lun=~\"$LUN\"} \n  and \ntopk($TopResources, avg_over_time(lun_write_data{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",lun=~\"$LUN\"}[3h] @ end()))",
       "legendFormat": "{{svm}} / {{volume}} / {{lun}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Luns by Write IOPs",
     "type": "timeseries",
     "description": "Number of write operations.",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "lun_write_ops{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",lun=~\"$LUN\"} \n  and \ntopk($TopResources, avg_over_time(lun_write_ops{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",lun=~\"$LUN\"}[3h] @ end()))",
       "legendFormat": "{{svm}} / {{volume}} / {{lun}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Top Volume Latency from QoS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Important Information on Top Volume QoS Latency Graphs",
     "type": "text",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
     "options": {
      "content": "This dashboard requires Workload/QOS counters templates. Two actions are required to use this dashboard: <br>\n1. If you are using ZapiPerf Collector, then On Harvest, You must enable the Workload/QOS counters in $HARVEST/conf/zapiperf/default.yaml. <br>\n2. If you are using RestPerf Collector, then On Harvest, You must enable the Workload/QOS counters in $HARVEST/conf/restperf/default.yaml. <br>\n\nRefer ONTAP Performance - Resolution Guide https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/ONTAP_9_Performance_-_Resolution_Guide"
     }
    },
    {
     "title": "Top $TopResources Volumes by Latency from Network",
     "type": "timeseries",
     "description": "average latency for workload on Data ONTAP subsystems.",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "qos_detail_resource_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",resource=\"network\",volume!=\"\"} \n  and \ntopk($TopResources, avg_over_time(qos_detail_resource_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",resource=\"network\",volume!=\"\"}[3h] @ end()))",
       "legendFormat": "{{svm}} / {{workload}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Latency from Throttle",
     "type": "timeseries",
     "description": "average latency for workload on Data ONTAP subsystems.",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "qos_detail_resource_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",resource=\"throttle\",volume!=\"\"} \n  and \ntopk($TopResources, avg_over_time(qos_detail_resource_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",resource=\"throttle\",volume!=\"\"}[3h] @ end()))",
       "legendFormat": "{{svm}} / {{workload}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Latency from Qos Min",
     "type": "timeseries",
     "description": "average latency for workload on Data ONTAP subsystems.",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "qos_detail_resource_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",resource=\"qos_min\",volume!=\"\"} \n  and \ntopk($TopResources, avg_over_time(qos_detail_resource_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",resource=\"qos_min\",volume!=\"\"}[3h] @ end()))",
       "legendFormat": "{{svm}} / {{workload}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Latency from Cluster",
     "type": "timeseries",
     "description": "average latency for workload on Data ONTAP subsystems.",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "qos_detail_resource_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",resource=\"cluster\",volume!=\"\"} \n  and \ntopk($TopResources, avg_over_time(qos_detail_resource_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",resource=\"cluster\",volume!=\"\"}[3h] @ end()))",
       "legendFormat": "{{svm}} / {{workload}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Latency from Backend",
     "type": "timeseries",
     "description": "average latency for workload on Data ONTAP subsystems.",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "qos_detail_resource_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",resource=\"backend\",volume!=\"\"} \n  and \ntopk($TopResources, avg_over_time(qos_detail_resource_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",resource=\"backend\",volume!=\"\"}[3h] @ end()))",
       "legendFormat": "{{svm}} / {{workload}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Latency from CP (Consistency Point)",
     "type": "timeseries",
     "description": "average latency for workload on Data ONTAP subsystems.",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "qos_detail_resource_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",resource=\"cp\",volume!=\"\"} \n  and \ntopk($TopResources, avg_over_time(qos_detail_resource_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",resource=\"cp\",volume!=\"\"}[3h] @ end()))",
       "legendFormat": "{{svm}} / {{workload}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Latency from Suspend",
     "type": "timeseries",
     "description": "average latency for workload on Data ONTAP subsystems.",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "qos_detail_resource_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",resource=\"suspend\",volume!=\"\"} \n  and \ntopk($TopResources, avg_over_time(qos_detail_resource_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",resource=\"suspend\",volume!=\"\"}[3h] @ end()))",
       "legendFormat": "{{svm}} / {{workload}} / {{volume}} "
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Latency from Cloud",
     "type": "timeseries",
     "description": "average latency for workload on Data ONTAP subsystems.",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "qos_detail_resource_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",resource=\"cloud\",volume!=\"\"} \n  and \ntopk($TopResources, avg_over_time(qos_detail_resource_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",resource=\"cloud\",volume!=\"\"}[3h] @ end()))",
       "legendFormat": "{{svm}} / {{workload}} / {{volume}} "
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Latency from Frontend",
     "type": "timeseries",
     "description": "average latency for workload on Data ONTAP subsystems.",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "qos_detail_resource_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",resource=\"frontend\",volume!=\"\"} \n  and \ntopk($TopResources, avg_over_time(qos_detail_resource_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",resource=\"frontend\",volume!=\"\"}[3h] @ end()))",
       "legendFormat": "{{svm}} / {{workload}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Latency from NVLog Mirroring",
     "type": "timeseries",
     "description": "average latency for workload on Data ONTAP subsystems.",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "qos_detail_resource_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",resource=\"nvlog\",volume!=\"\"} \n  and \ntopk($TopResources, avg_over_time(qos_detail_resource_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",resource=\"nvlog\",volume!=\"\"}[3h] @ end()))",
       "legendFormat": "{{svm}} / {{workload}} / {{volume}} "
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Latency from Disk",
     "type": "timeseries",
     "description": "average latency for workload on Data ONTAP subsystems.",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "qos_detail_resource_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",resource=\"disk\",volume!=\"\"} \n  and \ntopk($TopResources, avg_over_time(qos_detail_resource_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",resource=\"disk\",volume!=\"\"}[3h] @ end()))",
       "legendFormat": "{{svm}} / {{workload}} / {{volume}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Top Volume and LUN Capacity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopResources Volumes by Used %",
     "type": "timeseries",
     "description": "percentage of utilized storage space in a volume relative to its total capacity.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "volume_size_used_percent{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\"} \n  and \ntopk($TopResources, avg_over_time(volume_size_used_percent{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\"}[3h] @ end()))",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Snapshot Used %",
     "type": "timeseries",
     "description": "Percentage of snapshot reserve size that has been used.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "volume_snapshot_reserve_used_percent{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\"} \n  and \ntopk($TopResources, avg_over_time(volume_snapshot_reserve_used_percent{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\"}[3h] @ end()))",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Deduplication Percent Saved",
     "type": "timeseries",
     "description": "Percentage of the total disk space that is saved by deduplication and file cloning.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "volume_sis_dedup_saved_percent{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\"} \n  and \ntopk($TopResources, avg_over_time(volume_sis_dedup_saved_percent{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\"}[3h] @ end()))",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Compression Percent Saved",
     "type": "timeseries",
     "description": "Percentage of the total disk space that is saved by compressing blocks on the referenced file system.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "volume_sis_compress_saved_percent{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\"} \n  and \ntopk($TopResources, avg_over_time(volume_sis_compress_saved_percent{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\"}[3h] @ end()))",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources LUNs by Percent Most Filled",
     "type": "timeseries",
     "description": "LUN used percent.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "lun_size_used_percent{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",lun=~\"$LUN\"} \n  and \ntopk($TopResources, avg_over_time(lun_size_used_percent{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",lun=~\"$LUN\"}[3h] @ end()))",
       "legendFormat": "{{svm}} / {{volume}} / {{lun}}"
      }
     ]
    },
    {
     "title": "Top $TopResources LUNs by Percent Least Filled",
     "type": "timeseries",
     "description": "LUN used percent.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "lun_size_used_percent{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",lun=~\"$LUN\"} \n  and \nbottomk($TopResources, avg_over_time(lun_size_used_percent{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",lun=~\"$LUN\"}[3h] @ end()))",
       "legendFormat": "{{svm}} / {{volume}} / {{lun}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Per LUN (Must Select Cluster/SVM/Volume/LUN)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency",
     "type": "timeseries",
     "description": "This panels displays average read/write latency in microseconds for all operations on the LUN.",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "lun_avg_read_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",lun=~\"$LUN\"}",
       "legendFormat": "{{svm}} / {{volume}} / {{lun}} Read"
      },
      {
       "expr": "lun_avg_write_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",lun=~\"$LUN\"}",
       "legendFormat": "{{svm}} / {{volume}} / {{lun}} Write"
      }
     ]
    },
    {
     "title": "Throughput",
     "type": "timeseries",
     "description": "This panel displays Read/Write bytes data.",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "lun_read_data{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",lun=~\"$LUN\"}",
       "legendFormat": "{{svm}} / {{volume}} / {{lun}} Read"
      },
      {
       "expr": "lun_write_data{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",lun=~\"$LUN\"}",
       "legendFormat": "{{svm}} / {{volume}} / {{lun}} Write"
      }
     ]
    },
    {
     "title": "IOPs",
     "type": "timeseries",
     "description": "This panel displays number of read/write operations.",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "lun_read_ops{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",lun=~\"$LUN\"}",
       "legendFormat": "{{svm}} / {{volume}} / {{lun}} Read"
      },
      {
       "expr": "lun_write_ops{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",lun=~\"$LUN\"}",
       "legendFormat": "{{svm}} / {{volume}} / {{lun}} Write"
      }
     ]
    },
    {
     "title": "Indirect Access",
     "type": "timeseries",
     "description": "This panel displays detail of I/O to or from a LUN which is not owned by the storage system handling the I/O and number of operations received by a storage system that does not own the LUN targeted by the operations.",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "lun_remote_bytes{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",lun=~\"$LUN\"}",
       "legendFormat": "{{svm}} / {{volume}} / {{lun}} Remote Data"
      },
      {
       "expr": "lun_remote_ops{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",lun=~\"$LUN\"}",
       "legendFormat": "{{svm}} / {{volume}} / {{lun}} Remote IOPs"
      }
     ]
    },
    {
     "title": "vStorage Offload Operations",
     "type": "timeseries",
     "description": "This panel displays detail of number of compare and write requests, number of unmap command requests, number of write same command requests, number of write same commands requests with unmap bit set and total number of xcopy operations on the LUN.",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "lun_caw_reqs{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",lun=~\"$LUN\"}",
       "legendFormat": "Compare and Write"
      },
      {
       "expr": "lun_unmap_reqs{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",lun=~\"$LUN\"}",
       "legendFormat": "Unmap"
      },
      {
       "expr": "lun_writesame_reqs{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",lun=~\"$LUN\"}",
       "legendFormat": "Write Same"
      },
      {
       "expr": "lun_writesame_unmap_reqs{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",lun=~\"$LUN\"}",
       "legendFormat": "Write Same Unmap"
      },
      {
       "expr": "lun_xcopy_reqs{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",lun=~\"$LUN\"}",
       "legendFormat": "Xcopy"
      }
     ]
    },
    {
     "title": "IO Size",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "expr": "lun_read_data/lun_read_ops{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",lun=~\"$LUN\"}/1024",
       "legendFormat": "{{svm}} / {{volume}} / {{lun}} Read"
      },
      {
       "expr": "lun_write_data/lun_write_ops{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",volume=~\"$Volume|\",lun=~\"$LUN\"}/1024",
       "legendFormat": "{{svm}} / {{volume}} / {{lun}} Write"
      }
     ]
    }
   ]
  }
 ]
}