{
 "title": "FSxN: Utilization",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(dimension_FileSystemId)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Disk Operations",
   "type": "timeseries",
   "description": "Average latency in microseconds for the WAFL filesystem to process all the operations on the volume; not including request processing or network communication time.",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(aws_fsx_disk_read_operations_average{dimension_FileSystemId=~\"$Cluster\"}) by (dimension_FileSystemId)",
     "legendFormat": "{{dimension_FileSystemId}}_read_operations"
    },
    {
     "expr": "avg(aws_fsx_disk_write_operations_average{dimension_FileSystemId=~\"$Cluster\"}) by (dimension_FileSystemId)",
     "legendFormat": "{{dimension_FileSystemId}}_write_operations"
    },
    {
     "expr": "sum(aws_fsx_disk_write_operations_average{dimension_FileSystemId=~\"$Cluster\"} + aws_fsx_disk_read_operations_average{dimension_FileSystemId=~\"$Cluster\"}) by (dimension_FileSystemId)",
     "legendFormat": "{{dimension_FileSystemId}}_sum_operations"
    }
   ]
  },
  {
   "title": "Disk Throughput",
   "type": "timeseries",
   "description": "Average latency in microseconds for the WAFL filesystem to process all the operations on the volume; not including request processing or network communication time.",
   "gridPos": { "h": 13, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(aws_fsx_disk_write_bytes_average{dimension_FileSystemId=~\"$Cluster\"}) by (dimension_FileSystemId)  / 1048576",
     "legendFormat": "{{dimension_FileSystemId}}_write_megabytes"
    },
    {
     "expr": "avg(aws_fsx_disk_read_bytes_average{dimension_FileSystemId=~\"$Cluster\"}) by (dimension_FileSystemId)  / 1048576",
     "legendFormat": "{{dimension_FileSystemId}}_read_megabytes"
    },
    {
     "expr": "sum(aws_fsx_disk_read_bytes_average{dimension_FileSystemId=~\"$Cluster\"} + aws_fsx_disk_write_bytes_average{dimension_FileSystemId=~\"$Cluster\"} ) by (dimension_FileSystemId)",
     "legendFormat": "{{dimension_FileSystemId}}_sum_megabytes"
    }
   ]
  },
  {
   "title": "Utilization Percentage",
   "type": "timeseries",
   "description": "Average latency in microseconds for the WAFL filesystem to process all the operations on the volume; not including request processing or network communication time.",
   "gridPos": { "h": 19, "w": 11, "x": 5, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(aws_fsx_disk_iops_utilization_average{dimension_FileSystemId=~\"$Cluster\"}) by (dimension_FileSystemId)",
     "legendFormat": "{{dimension_FileSystemId}}_iops_utilization"
    },
    {
     "expr": "avg(aws_fsx_network_throughput_utilization_average{dimension_FileSystemId=~\"$Cluster\"}) by (dimension_FileSystemId)",
     "legendFormat": "{{dimension_FileSystemId}}_network_throughput_utilization"
    },
    {
     "expr": "sum(aws_fsx_file_server_disk_throughput_utilization_average{dimension_FileSystemId=~\"$Cluster\"} + aws_fsx_disk_write_bytes_average{dimension_FileSystemId=~\"$Cluster\"} ) by (dimension_FileSystemId)",
     "legendFormat": "{{dimension_FileSystemId}}_disk_throughput_utilization"
    }
   ]
  }
 ]
}